name:                terminal-config-manager
version:             0.1.0.0
github:              "githubuser/terminal-config-manager"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/terminal-config-manager#readme>

default-extensions: DerivingStrategies OverloadedStrings DeriveGeneric PatternSynonyms

dependencies:
- base >= 4.7 && < 5
- brick
- vty
- cursor
- text
- yaml
- strict
- optparse-applicative
- aeson

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wmonomorphism-restriction
    - -Wmissing-local-signatures
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Widentities
    - -Wredundant-constraints
    - -Wpartial-fields
    - -Wcpp-undef
    - -Wmissing-deriving-strategies
    - -Wunused-packages
    - -Wunused-type-patterns
    - -Wcompat

executables:
  terminal-config-manager:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal-config-manager

tests:
  terminal-config-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal-config-manager
    - hspec
    - QuickCheck
