name: build+tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 8 * * 1"

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Cache dependencies (Unix)
      uses: actions/cache@v4
      with:
        path: ~/.stack
        key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('terminal-config-manager.cabal') }}
    - name: build and run all tests (unit + integration)
      run: stack build --test
